[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bash start-server.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[env]
NODE_ENV = "production"

# Build configuration
[build.nixpacksConfig]
aptPkgs = ["nodejs", "npm"]
npmConfigProduction = false

# Service configuration
[service]
# Railway will automatically handle this